### ISSUE TITLE
elixir: Fix build process

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/messages#126]
### 🤔 What's the problem you've observed?

[Elixir fails to release](https://github.com/cucumber/messages/actions/runs/3719910333/jobs/6309058962). The release runs on ubuntu-latest which is now Ubuntu 22.04. This means that OTP 22.2 is no longer available.

### 📚 Any additional context?

This is the same problem as https://github.com/cucumber/gherkin/pull/72 but we only see it in release here because  build containers are not representative for the release process (#125).

I've disabled the release process in 17a3298b9ba716d4c138436cb1b5dfb0dce74bfa.

**Comment by ciaranmcnulty** [comment]
one issue is that the hex release action doesn't test against the same OTP + elixir versions we are using, see [#6](https://github.com/cucumber/action-publish-hex/pull/6/files)
