### ISSUE TITLE
Cannot import Messages from '@cucumber/messages';

### ISSUE THREAD

**Issue by kobenguyent** [cucumber/messages#208]
### 👓 What did you see?

When trying to import Messages from '@cucumber/messages';
I got the error

```
file:///Users/t/Desktop/projects/CodeceptJS/lib/interfaces/gherkin.js:3
import Messages from '@cucumber/messages';
       ^^^^^^^^
SyntaxError: The requested module '@cucumber/messages' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)


```

### 📦 Which tool/library version are you using?
"@cucumber/messages": "24.0.1"

**Comment by mpkorstanje** [comment]
The error message looks accurate, why do think this a problem?

**Comment by mpkorstanje** [comment]
Ah, I'm not to deep into JS but the messages module doesn't have a default export. So you either have to import the individual classes or the whole namespace.

So I believe that  one of these should work:

```js
import * as messages from "@cucumber/messages"
```

```js
import { Background, Feature, GherkinDocument, Rule, Scenario, Step } from '@cucumber/messages'
```

They both show up in other cucumber projects and match with the MDN docs. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
