### ISSUE TITLE
Python cuke-messages bad Pydantic model for ExceptionMessage

### ISSUE THREAD

**Issue by sashokbg** [cucumber/messages#263]
### 👓 What did you see?

Using cuke-messages 0.1.0 the ExceptionMessage type does not define the stackTrace field and having "extra" set to "forbid" causes an error

### ✅ What did you expect to see?

The missing property should be there

**Comment by mpkorstanje** [comment]
That should probably go to https://github.com/elchupanebrej/messages. It's still a work in progress on https://github.com/cucumber/messages/pull/165. 

@elchupanebrej would you mind fixing the meta info on the package you published so it doesn't point here just yet.

**Comment by sashokbg** [comment]
Ah now I see it is actually a fork.
I will tell the person on the other repo to change the URL. Cheers !

**Comment by elchupanebrej** [comment]
@mpkorstanje , sorry for the inconvenience,  I'll do it, and I have to find time to finish #165.
