### ISSUE TITLE
Is it intended that C++ headers are in e.g. /usr/include/cucumber/cucumber/messages/ ?

### ISSUE THREAD

**Issue by musicinmybrain** [cucumber/messages#267]
### 👓 What did you see?

In a fresh checkout:

```
$ cd cpp/
$ cmake -S. -Bbuild
$ cmake --build build
$ DESTDIR=foo cmake --install build
$ find foo/ -name all.hpp
foo/usr/local/include/cucumber/cucumber/messages/all.hpp
```

### ✅ What did you expect to see?

I’m surprised that headers aren’t installed in e.g. `/usr/include/cucumber/messages/` rather than `/usr/include/cucumber/cucumber/messages/`. Is this intentional?

### 📦 Which tool/library version are you using?

Current `main`, 9114562c0bea318c1238085cec64e9587971443e.

### 🔬 How could we reproduce it?

See **What did you see?**, above.

### 📚 Any additional context?

The additional `cucumber/` seems to be handled in `cucumber_messages-targets.cmake`, which has

```cmake
set_target_properties(cucumber::messages PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/cucumber"
  […]
)
```

but the `cucumber/cucumber` still seems like it might have been an accident.

**Comment by mpkorstanje** [comment]
@chybz @jenisys I think you could comment on this?

**Comment by musicinmybrain** [comment]
If it’s not intentional, it seems like

```diff
--- a/cpp/CMakeLists.txt
+++ b/cpp/CMakeLists.txt
@@ -140,5 +140,5 @@ install(
 
 install(
     DIRECTORY "${PROJECT_SOURCE_DIR}/include/messages/"
-    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/cucumber
+    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
 )
```

would fix it.

**Comment by musicinmybrain** [comment]
Thank you very much for the explanation, which makes perfect sense.

Given that the structure is intentional, there is no problem with it at all.
