### ISSUE TITLE
Releases are (probably) not triggering the packagist web hook

### ISSUE THREAD

**Issue by ciaranmcnulty** [cucumber/messages#52]
`19.1.3` was not visible on packagist until I hit the Update button over there

`messages-php` has the web hook, it may need extra config to be triggered from a workflow run?

**Comment by mattwynne** [comment]
19.1.4 seems to have made it into https://packagist.org/packages/cucumber/messages unaided. I'll close this.

**Comment by ciaranmcnulty** [comment]
Packaging was having a backlog processing webhooks on the day in question, it looks like

**Comment by ciaranmcnulty** [comment]
Knightsbridgd
