### ISSUE TITLE
Migrate dotnet to new JSON Schema-based messages

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/messages#64]
Ruby, JS, JVM and other implementation have migrated from protobuf to JSON Schema based messages.

Refs. cucumber/common#1386

**Comment by luke-hill** [comment]
ping @clrudolphi - Are we happy closing this off as completed?

**Comment by clrudolphi** [comment]
> ping @clrudolphi - Are we happy closing this off as completed?

Yes thanks.
