### ISSUE TITLE
Messages Perl - did not regenerate during make

### ISSUE THREAD

**Issue by ciaranmcnulty** [cucumber/messages#99]
I edited the JSON schema as part of cucumber/common#1923  and did `make clean; make` inside `/messages`

The Perl implementation did not update - I had to manually delete `messages/perl/lib/Cucumber/Messages.pm` and run the make again

This should be something that's done during the build otherwise we'll drop out of sync when more important changes are made

**Comment by luke-hill** [comment]
I believe this is now done. I have done some edits in `perl` recently (Just cosmetic), and both `make generate-all` at the top level as well as `cd perl; make generate` both worked fine.

I'm closing this off as completed.
